---
title: "Coursera: Practical Machine Learning"
author: "Tom Ilchef"
date: "25/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load libraries 
```{r}
library(tidyr)
library(caret)
library(dplyr)
library(dlookr)
library(GGally)
library(plotly)
```

Acquire Data
```{r}
final_test_df <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")
training_raw_df <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
```


split training into test train 
```{r}
xval_split  <- createDataPartition(training_raw_df$classe
                                , p=0.75
                                , list=FALSE)
train <- training_raw_df[xval_split, ]
test  <- training_raw_df[-xval_split, ]
```

data cleaning
```{r}
# removing variables that have more than 5% nulls

t_desc <- describe(train)%>%
        filter(na <= nrow(!!train)*0.05) %>%
        pull(variable) 

# also going to remove ID variables manually. 
train <- train %>%
        select(!!t_desc) %>%
        select(-c("X","raw_timestamp_part_1","raw_timestamp_part_2"))

test <- test %>%
        select(!!t_desc) %>%
        select(-c("X","raw_timestamp_part_1","raw_timestamp_part_2"))

```

Exploratory Data Analysis
```{r}
panel.hist <- function(x, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5))
    his <- hist(x, plot = FALSE)
    breaks <- his$breaks
    nB <- length(breaks)
    y <- his$counts
    y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = rgb(0, 1, 1, alpha = 0.5), ...)
    # lines(density(x), col = 2, lwd = 2) # Uncomment to add density lines
}

pairs(train,
      upper.panel = NULL,         # Disabling the upper panel
      diag.panel = panel.hist)    # Adding the histograms
pairs



cor(train) %>% 
  as.data.frame() %>% 
  ggcorr(low = "red"
         , mid = "grey"
         , high = "green") %>%
  ggplotly()
```